image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Run gitStream
        script:
          - pipe: docker://linear-b/gitstream-bitbucket-pipe:latest
            variables:
              GITSTREAM_CONFIG_PATH: '.cm/gitstream.cm'
              GITSTREAM_API_TOKEN: $GITSTREAM_API_TOKEN
